channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.3.1
- pip:
  - mlflow==2.14.1
  - cloudpickle==3.0.0
  - lz4==4.3.3
  - numpy==1.23.5
  - packaging==23.2
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.1.1
  - scipy==1.10.0
name: mlflow-env
